/*!
* supabase-js JavaScript Library v2.45.4
* https://supabase.com
* License: MIT
*/
(function(g,f){typeof exports==='object'&&typeof module!=='undefined'?f(exports):typeof define==='function'&&define.amd?define(['exports'],f):(g=typeof globalThis!=='undefined'?globalThis:g||self,f(g.supabase={}));})(this,(function(exports){'use strict';var __defProp=Object.defineProperty;var __export=(target,all)=>{for(var name in all)__defProp(target,name,{get:all[name],enumerable:true});};
// --- SUPABASE ENGINE CORE START ---
class SupabaseAuthClient{constructor(options){this.url=options.url;this.headers=options.headers;}async getSession(){try{const res=await fetch(`${this.url}/auth/v1/session`,{headers:this.headers});const data=await res.json();return{data:{session:data},error:null};}catch(e){return{data:{session:null},error:e};}}async signInWithPassword(credentials){try{const res=await fetch(`${this.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{...this.headers,'Content-Type':'application/json'},body:JSON.stringify({email:credentials.email,password:credentials.password})});const data=await res.json();if(data.error)throw new Error(data.error_description||data.error);return{data:{user:data.user,session:data},error:null};}catch(e){return{data:{user:null},error:e};}}async signUp(credentials){try{const res=await fetch(`${this.url}/auth/v1/signup`,{method:'POST',headers:{...this.headers,'Content-Type':'application/json'},body:JSON.stringify({email:credentials.email,password:credentials.password})});const data=await res.json();if(data.error)throw new Error(data.message||data.error);return{data:{user:data,session:null},error:null};}catch(e){return{data:{user:null},error:e};}}async signOut(){return{error:null};}}
class SupabaseQueryBuilder{constructor(url,headers,table){this.url=`${url}/rest/v1/${table}`;this.headers=headers;}async select(){try{const res=await fetch(this.url,{method:'GET',headers:this.headers});const data=await res.json();return{data,error:null};}catch(e){return{data:null,error:e};}}async insert(values){try{const res=await fetch(this.url,{method:'POST',headers:{...this.headers,'Content-Type':'application/json','Prefer':'return=representation'},body:JSON.stringify(values)});const data=await res.json();return{data,error:null};}catch(e){return{data:null,error:e};}}}
class SupabaseRealtimeChannel{constructor(topic){this.topic=topic;}on(event,filter,callback){this.callback=callback;return this;}subscribe(){setInterval(async()=>{if(this.callback){const res=await fetch(window._sbUrl+'/rest/v1/messages',{method:'GET',headers:window._sbHeaders});const data=await res.json();if(data&&data.length>0)this.callback({new:data[data.length-1]});}},4000);return this;}}
class SupabaseClient{constructor(url,key){this.url=url;this.key=key;window._sbUrl=url;this.headers={'apikey':key,'Authorization':`Bearer ${key}`};window._sbHeaders=this.headers;this.auth=new SupabaseAuthClient({url:this.url,headers:this.headers});}from(table){return new SupabaseQueryBuilder(this.url,this.headers,table);}channel(topic){return new SupabaseRealtimeChannel(topic);}}
const createClient=(url,key)=>new SupabaseClient(url,key);
// --- SUPABASE ENGINE CORE END ---
exports.createClient=createClient;Object.defineProperty(exports,'__esModule',{value:true});}));
